### PR TITLE
CORE-1755: added the endpoint to allow service accounts to update user plans

### PR DESCRIPTION
**Pull request by slr71**

### CODE REVIEW

**Comment by slr71** [comment]
I found the problem that I was encountering yesterday. The `/admin` element had been removed from some URL paths in the QMS service, and Terrain hadn't  been updated yet. I updated the QMS client namespace to also remove that element from the service calls.

**Review by johnworth — APPROVED** [review]
:shipit

**Review by psarando — COMMENTED** [review]
LGTM 👍

**Comment by slr71** [comment]
Thanks for the reviews!

**Pull request merged**
